name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Code Linting
        run: pylint scripts/*.py --errors-only

      - name: Confirm Black code compliance
        run: |
          black scripts/

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'

      - name: Run Tests
        run: python -m unittest discover scripts/tests/

  continuous-deployment:
    needs: continuous-integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
           echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
           ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
           sudo apt install python3 &&
           git clone https://github.com/oflorez1381/python_ci_cd_terraform.git &&
           cd python_ci_cd_terraform  &&
           git checkout main &&
           git fetch --all &&
           git reset --hard origin/main &&
           git pull origin main &&
           cd scripts &&
           python3 fetch_jobs.py &&
           rm -r /home/ubuntu/python_ci_cd_terraform
           '